// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using QUAN_LY.UI.Data;

#nullable disable

namespace QUAN_LY.UI.Migrations
{
    [DbContext(typeof(LibraryContext))]
    partial class LibraryContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("QUAN_LY.UI.Models.Admin", b =>
                {
                    b.Property<int>("MaNhanVien")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaNhanVien"));

                    b.Property<string>("Anhcanhan")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Chucvu")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DiaChi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GioiTinh")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Matkhau")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("NgaySinh")
                        .HasColumnType("datetime2");

                    b.Property<string>("SoDienThoai")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Tendangnhap")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaNhanVien");

                    b.ToTable("Admins");

                    b.HasData(
                        new
                        {
                            MaNhanVien = -1,
                            Chucvu = "Admin",
                            HoTen = "Trường Giang",
                            Matkhau = "$2a$11$bBw6KOAmlVKN9ibkK95KGex8ctfk0SRNiN3fXwL8m6iFPQW.TuF8i",
                            Tendangnhap = "Admin0811"
                        });
                });

            modelBuilder.Entity("QUAN_LY.UI.Models.ChiTietMuonSach", b =>
                {
                    b.Property<int>("MaChiTietMuon")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaChiTietMuon"));

                    b.Property<string>("GhiChu")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("HanTra")
                        .HasColumnType("datetime2");

                    b.Property<int>("MaMuon")
                        .HasColumnType("int");

                    b.Property<int>("MaSach")
                        .HasColumnType("int");

                    b.Property<DateTime?>("NgayMuon")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("NgayTra")
                        .HasColumnType("datetime2");

                    b.Property<int>("SoLuong")
                        .HasColumnType("int");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaChiTietMuon");

                    b.HasIndex("MaMuon");

                    b.HasIndex("MaSach");

                    b.ToTable("ChiTietMuonSach");
                });

            modelBuilder.Entity("QUAN_LY.UI.Models.Giohang", b =>
                {
                    b.Property<int>("MaGioHang")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaGioHang"));

                    b.Property<int>("MaKhachHang")
                        .HasColumnType("int");

                    b.Property<int?>("MaMuon")
                        .HasColumnType("int");

                    b.Property<int>("MaSach")
                        .HasColumnType("int");

                    b.Property<int>("SoLuongmuon")
                        .HasColumnType("int");

                    b.HasKey("MaGioHang");

                    b.HasIndex("MaKhachHang");

                    b.HasIndex("MaMuon");

                    b.HasIndex("MaSach");

                    b.ToTable("Giohang");
                });

            modelBuilder.Entity("QUAN_LY.UI.Models.HiddenHistories", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("MaChiTietMuon")
                        .HasColumnType("int");

                    b.Property<int>("MaKhachHang")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MaChiTietMuon");

                    b.HasIndex("MaKhachHang");

                    b.ToTable("HiddenHistories");
                });

            modelBuilder.Entity("QUAN_LY.UI.Models.KhachHang", b =>
                {
                    b.Property<int>("MaKhachHang")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaKhachHang"));

                    b.Property<string>("Anhcanhan")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DiaChi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GioiTinh")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Matkhau")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("NgaySinh")
                        .HasColumnType("datetime2");

                    b.Property<string>("SoDienThoai")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Tendangnhap")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaKhachHang");

                    b.ToTable("KhachHang");
                });

            modelBuilder.Entity("QUAN_LY.UI.Models.MuonSach", b =>
                {
                    b.Property<int>("MaMuon")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaMuon"));

                    b.Property<string>("GhiChu")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MaKhachHang")
                        .HasColumnType("int");

                    b.Property<DateTime?>("NgayYeuCau")
                        .HasColumnType("datetime2");

                    b.Property<int>("Soluong")
                        .HasColumnType("int");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaMuon");

                    b.HasIndex("MaKhachHang");

                    b.ToTable("MuonSach");
                });

            modelBuilder.Entity("QUAN_LY.UI.Models.Sach", b =>
                {
                    b.Property<int>("MaSach")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaSach"));

                    b.Property<string>("Mota")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("NgayNhap")
                        .HasColumnType("datetime2");

                    b.Property<string>("NhaXuatBan")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SoLuongMuon")
                        .HasColumnType("int");

                    b.Property<int>("SoLuongTon")
                        .HasColumnType("int");

                    b.Property<string>("TacGia")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TheLoai")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Thoihanmuon")
                        .HasColumnType("int");

                    b.Property<string>("TieuDe")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaSach");

                    b.ToTable("Sach");
                });

            modelBuilder.Entity("QUAN_LY.UI.Models.ChiTietMuonSach", b =>
                {
                    b.HasOne("QUAN_LY.UI.Models.MuonSach", "MuonSach")
                        .WithMany("ChiTietMuonSaches")
                        .HasForeignKey("MaMuon")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QUAN_LY.UI.Models.Sach", "Sach")
                        .WithMany("ChiTietMuonSaches")
                        .HasForeignKey("MaSach")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MuonSach");

                    b.Navigation("Sach");
                });

            modelBuilder.Entity("QUAN_LY.UI.Models.Giohang", b =>
                {
                    b.HasOne("QUAN_LY.UI.Models.KhachHang", "KhachHang")
                        .WithMany("Giohangs")
                        .HasForeignKey("MaKhachHang")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QUAN_LY.UI.Models.MuonSach", "MuonSach")
                        .WithMany("Giohangs")
                        .HasForeignKey("MaMuon");

                    b.HasOne("QUAN_LY.UI.Models.Sach", "Sach")
                        .WithMany("Giohangs")
                        .HasForeignKey("MaSach")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("KhachHang");

                    b.Navigation("MuonSach");

                    b.Navigation("Sach");
                });

            modelBuilder.Entity("QUAN_LY.UI.Models.HiddenHistories", b =>
                {
                    b.HasOne("QUAN_LY.UI.Models.ChiTietMuonSach", "ChiTietMuonSach")
                        .WithMany("HiddenHistories")
                        .HasForeignKey("MaChiTietMuon")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QUAN_LY.UI.Models.KhachHang", "KhachHang")
                        .WithMany("HiddenHistories")
                        .HasForeignKey("MaKhachHang")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("ChiTietMuonSach");

                    b.Navigation("KhachHang");
                });

            modelBuilder.Entity("QUAN_LY.UI.Models.MuonSach", b =>
                {
                    b.HasOne("QUAN_LY.UI.Models.KhachHang", "KhachHang")
                        .WithMany("MuonSaches")
                        .HasForeignKey("MaKhachHang")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("KhachHang");
                });

            modelBuilder.Entity("QUAN_LY.UI.Models.ChiTietMuonSach", b =>
                {
                    b.Navigation("HiddenHistories");
                });

            modelBuilder.Entity("QUAN_LY.UI.Models.KhachHang", b =>
                {
                    b.Navigation("Giohangs");

                    b.Navigation("HiddenHistories");

                    b.Navigation("MuonSaches");
                });

            modelBuilder.Entity("QUAN_LY.UI.Models.MuonSach", b =>
                {
                    b.Navigation("ChiTietMuonSaches");

                    b.Navigation("Giohangs");
                });

            modelBuilder.Entity("QUAN_LY.UI.Models.Sach", b =>
                {
                    b.Navigation("ChiTietMuonSaches");

                    b.Navigation("Giohangs");
                });
#pragma warning restore 612, 618
        }
    }
}
